name: Dist Dotnet Validate
on:
  workflow_call:

jobs:
  validate:
    uses: ./.github/workflows/dotnet-common.yml
    with:
      create_release: false
      enforce_format: false
      publish_output: publish
